source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/bidon-io/CocoaPods-Specs.git'
source 'https://cdn.cocoapods.org'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require 'pathname'
require 'uri'

# RN 0.85 prebuilt pod helpers can fail to build file:// URIs for absolute local
# tarball paths when the workspace path contains spaces.
module LocalFileUriBuildFallback
  def build(args)
    super
  rescue URI::InvalidComponentError => error
    path = args.is_a?(Hash) ? args[:path] : nil
    raise error unless path.is_a?(String) && Pathname.new(path).absolute?

    URI.parse(URI::DEFAULT_PARSER.escape("file://#{Pathname.new(path).expand_path}"))
  end
end

unless URI::File.singleton_class.ancestors.include?(LocalFileUriBuildFallback)
  URI::File.singleton_class.prepend(LocalFileUriBuildFallback)
end

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS'] || 'static'
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym
$RNFirebaseAsStaticFramework = true

target 'PlayCall' do
  use_expo_modules!(exclude: ['expo'])

  # Firebase Swift pods are integrated as static libraries in this project.
  # These transitive dependencies need module maps for CocoaPods to compile them.
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseABTesting', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseRemoteConfig', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      if target.name.start_with?('RNFB')
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end

        prefix_header_path = File.join(__dir__, 'Pods', 'Target Support Files', target.name, "#{target.name}-prefix.pch")
        if File.exist?(prefix_header_path)
          prefix_header = File.read(prefix_header_path)
          required_imports = [
            '#import <React/RCTBridgeModule.h>',
            '#import <React/RCTEventEmitter.h>'
          ]
          missing_imports = required_imports.reject { |line| prefix_header.include?(line) }

          unless missing_imports.empty?
            File.open(prefix_header_path, 'a') do |file|
              file.puts
              missing_imports.each { |line| file.puts(line) }
            end
          end
        end
      end

      if target.name == 'RNStoreReview'
        target.build_configurations.each do |config|
          header_search_paths = config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
          header_search_paths = [header_search_paths] unless header_search_paths.is_a?(Array)
          header_search_paths << '$(OBJECT_FILE_DIR_normal)/$(CURRENT_ARCH)'
          config.build_settings['HEADER_SEARCH_PATHS'] = header_search_paths.uniq
        end
      end

      next unless target.name == 'EXConstants'

      target.shell_script_build_phases.each do |phase|
        next unless phase.name == '[CP-User] Generate app.config for prebuilt Constants.manifest'

        phase.shell_script = 'bash -l "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"'
      end
    end
  end
end
